export type Player = {
    assists: number,
    champLevel: number,
    championName: string,
    consumablesPurchased: number,
    damageSelfMitigated: number,
    deaths: number,
    goldEarned: number,
    goldSpent: number,
    item0: number,
    item1: number,
    item2: number,
    item3: number,
    item4: number,
    item5: number,
    item6: number,
    itemsPurchased: number,
    kills: number,
    largestCriticalStrike: number,
    magicDamageDealt: number,
    magicDamageDealtToChampions: number,
    magicDamageTaken: number,
    physicalDamageDealt: number,
    physicalDamageDealtToChampions: number,
    physicalDamageTaken: number,
    placement: number,
    playerAugment1: number,
    playerAugment2: number,
    playerAugment3: number,
    playerAugment4: number,
    playerAugment5: number,
    playerAugment6: number,
    profileIcon: number,
    puuid: string,
    riotIdGameName: string,
    riotIdTagline: string,
    spell1Casts: number,
    spell2Casts: number,
    spell3Casts: number,
    spell4Casts: number,
    subteamPlacement: number,
    summoner1Casts: number,
    summoner1Id: number,
    summoner2Casts: number,
    summoner2Id: number,
    summonerId: string,
    summonerLevel: number,
    totalDamageDealt: number,
    totalDamageDealtToChampions: number,
    totalDamageShieldedOnTeammates: number,
    totalDamageTaken: number,
    totalHeal: number,
    totalHealsOnTeammates: number,
    totalTimeCCDealt: number,
    totalTimeSpentDead: number,
    trueDamageDealt: number,
    trueDamageDealtToChampions: number,
    trueDamageTaken: number,
    challenges: {
      abilityUses: number,
      skillshotsDodged: number,
      skillshotsHit: number,
    }
};

type Duo = {
    duoPuuid: string | null,
    duoRiotIdGameName: string | null,
    duoRiotIdTagline: string | null,
}

export type PlayerWithDuo = Player & {
  duoData: {
    duo: Duo
  }
}